region               = "us-east-2"
engine               = "mysql"
engine_version       = "5.7"
instance_class       = "db.t3.micro"
name                 = "mydb"
username             = "unimed"
password             = "9sy1¨#msa9&23"
parameter_group_name = "default.mysql5.7"
