version: 0.2
        phases:
            install:
                commands:
                - "cd /usr/bin"
                - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/$${TF_VERSION}/terraform_$${TF_VERSION}_linux_amd64.zip"
                - "unzip -o terraform.zip"
            build:
                commands:
                - echo Terraform deployment started on `date`
                - cd "$CODEBUILD_SRC_DIR/infra"
                - echo "terraform" { > backend.tf
                - echo "   backend \"s3\" {} " >> backend.tf
                - echo "}" >> backend.tf
                - terraform init -input=false --backend-config="bucket=${aws_s3_bucket.tfstate_bucket.id}" --backend-config="key=${var.source_repo_name}-${var.source_repo_branch}.tfsate" --backend-config="region=${data.aws_region.current.name}"
                - terraform apply -input=false -var-file=./terraform.tfvars -auto-approve
            post_build:
                commands:
                - echo "Terraform completed on `date`"