version: 0.2
        env:
          exported-variables: 
              - BuildID
              - BuildTag
              - Region
              - checks_errors
              - check_high
              - check_warning
              - check_low
        phases:
            pre_build:
                commands:
                - echo "Executing tfsec"
                - mkdir -p $CODEBUILD_SRC_DIR/infra/tfsec/
            build:
                commands:
                - tfsec --version
                - cd $CODEBUILD_SRC_DIR/infra
                - tfsec -s --tfvars-file terraform.tfvars --format junit > tfsec/report.xml
                - num_errors=$(tfsec -s --tfvars-file terraform.tfvars |  grep ERROR | wc -l)
                - num_high=$(tfsec -s --tfvars-file terraform.tfvars |  grep HIGH | wc -l)
                - num_warning=$(tfsec -s --tfvars-file terraform.tfvars |  grep WARNING | wc -l)
                - num_low=$(tfsec -s --tfvars-file terraform.tfvars |  grep LOW | wc -l)
                - export BuildID=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f1)
                - export BuildTag=$(echo $CODEBUILD_BUILD_ID | cut -d':' -f2)
                - export Region=$AWS_DEFAULT_REGION
                - export checks_errors=$num_errors
                - export check_high=$num_high
                - export check_warning=$num_warning
                - export check_low=$num_low
        reports:
            tfsec-reports:
              files: 
                - infra/tfsec/*.xml
              file-format: "JUNITXML"