version: 0.2
        phases:
            pre_build:
                commands:
                - echo "Executing tflint"
                - mkdir -p $CODEBUILD_SRC_DIR/infra/tflint/
                - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            build:
                commands:
                - cd "$CODEBUILD_SRC_DIR/infra"
                - tflint --init
                - ls
                - tflint -f junit > "tflint/tflint_report.xml"
                - ls tflint
        reports:
            tflint:
              files:
                - infra/tflint/*.xml
              file-format": "JUNITXML"